"""3 версия

Revision ID: 94cee06f8577
Revises: fc94a9a01b8b
Create Date: 2024-04-01 17:21:42.990587

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94cee06f8577'
down_revision: Union[str, None] = 'fc94a9a01b8b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('feedback_client_id_fkey', 'feedback', type_='foreignkey')
    op.drop_column('feedback', 'client_id')
    op.drop_column('order', 'cost')
    op.drop_column('order', 'dish')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('dish', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('order', sa.Column('cost', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('feedback', sa.Column('client_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('feedback_client_id_fkey', 'feedback', 'client', ['client_id'], ['id'])
    # ### end Alembic commands ###
