"""попытка 4

Revision ID: ee4ec1d0d602
Revises: 94cee06f8577
Create Date: 2024-04-01 18:07:00.385011

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee4ec1d0d602'
down_revision: Union[str, None] = '94cee06f8577'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dish',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('cost', sa.Float(), nullable=True),
    sa.Column('type', sa.String(length=20), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('restaurant_id', sa.SmallInteger(), nullable=True),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Dish_Order',
    sa.Column('dish_id', sa.Integer(), nullable=True),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['dish_id'], ['dish.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], )
    )
    op.drop_table('DisheOrder')
    op.drop_table('dishe')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dishe',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('dishe_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('cost', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('type', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('restaurant_id', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurant.id'], name='dishe_restaurant_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='dishe_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('DisheOrder',
    sa.Column('dishe_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('order_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['dishe_id'], ['dishe.id'], name='DisheOrder_dishe_id_fkey'),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], name='DisheOrder_order_id_fkey')
    )
    op.drop_table('Dish_Order')
    op.drop_table('dish')
    # ### end Alembic commands ###
