"""вторая версия

Revision ID: fc94a9a01b8b
Revises: 48f326401421
Create Date: 2024-04-01 00:10:03.570187

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc94a9a01b8b'
down_revision: Union[str, None] = '48f326401421'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('DisheOrder',
    sa.Column('dishe_id', sa.Integer(), nullable=True),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['dishe_id'], ['dishe.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], )
    )
    op.drop_table('dishe_order')
    op.alter_column('client', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True,
               existing_server_default=sa.text("nextval('client_id_seq'::regclass)"))
    op.alter_column('client', 'chat_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=True)
    op.alter_column('feedback', 'author',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('feedback', 'client_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('order', 'client_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('order', 'client_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.alter_column('feedback', 'client_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.alter_column('feedback', 'author',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.alter_column('client', 'chat_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('client', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True,
               existing_server_default=sa.text("nextval('client_id_seq'::regclass)"))
    op.create_table('dishe_order',
    sa.Column('dishe_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('order_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['dishe_id'], ['dishe.id'], name='dishe_order_dishe_id_fkey'),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], name='dishe_order_order_id_fkey'),
    sa.PrimaryKeyConstraint('dishe_id', 'order_id', name='dishe_order_pkey')
    )
    op.drop_table('DisheOrder')
    # ### end Alembic commands ###
